[profile.default]
solc_version = "0.8.26"
src = "src"
out = "out"
libs = ["lib"]
memory_limit = 6500000000
gas_limit = "18446744073709551615" # u64::MAX

fs_permissions = [{ access = "read", path = "./inputs/"}] 